version: '3'
services:
  db:
    build: ./database
    image: flyway-db
    restart: always
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306