version: '3'
services:
  mysql:
    build: ./mysql
    image: doma-mysql
    restart: always
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    container_name: doma-mysql-container
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d