server:
  port: 8080
  servlet:
    context-path: /demo

security:
  oauth2:
    client:
      client-id: XXX
      client-secret: XXX
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false
    sso:
      login-path: /login
