spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbname
    username: name
    password: pass
mybatis:
  mapper-locations: classpath:/com/example/app/mapper/*.xml